### PR TITLE
:/ how do i fix

### PR DESCRIPTION
**Pull request by Tavish-153**
how do i fix this?????
Traceback (most recent call last):
  File "builder.py", line 5, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

### CODE REVIEW

**Comment by Xalri** [comment]
same

**Comment by modpotato** [comment]
install the pip crypto package

**Comment by abesiregar** [comment]
even after "pip install cryptography" the error still happens

**Comment by NeutralOuija** [comment]
Would someone be able to help? i cannot get past the bypass security step

**Comment by MikeyMadisonwife** [comment]
how can i fix " File "builder.py", line 12, in <module>
    good = f"{Fore.GREEN}[+]{Style.RESET_ALL}"
NameError: name 'Fore' is not defined" I installed everything but it still shows it

**Comment by modpotato** [comment]
> 

sounds like its from colorama

**Comment by dish0m** [comment]
how do i fix Build Error: b'wine: cannot find L"/root/.wine/drive_c/users/root/Local Settings/Application Data/Programs/Python/Python38-32/Scripts/pyinstaller.exe"
'

**Comment by ghost** [comment]
try
pip install Fernet

**Comment by PandoricGalaxy** [comment]
[-] Build Error: [WinError 2] The system cannot find the file specified ???
comes when building the grabber

**Comment by PandoricGalaxy** [comment]
> even after "pip install cryptography" the error still happens

cd into the eclipse-grabber directory then pip install cryptography

**Comment by DaTrueCat** [comment]
bruh i have the same issue and i cannot fix it whatever i do
File "builder.py", line 5, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

**Comment by gugasz** [comment]
I have this error whenever I try to run the command. Tried multiple things, but couldn't fix it.
Traceback (most recent call last):
  File "builder.py", line 5, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

**Comment by Tavish-153** [comment]
STOP COMMENTING AND TELL ME THE ANSWER IDIOTS

**Comment by Tavish-153** [comment]
GO OPEN YOUR OWN ISSUE AMD IM CLOSING THIS ISSUE

**Comment by PandoricGalaxy** [comment]
> how do i fix this????? Traceback (most recent call last): File "builder.py", line 5, in from cryptography.fernet import Fernet ModuleNotFoundError: No module named 'cryptography'

Just cd into the eclipse builder dir then pip install cryptography

**Comment by DaTrueCat** [comment]
> > how do i fix this????? Traceback (most recent call last): File "builder.py", line 5, in from cryptography.fernet import Fernet ModuleNotFoundError: No module named 'cryptography'
> 
> Just cd into the eclipse builder dir then pip install cryptography

doesnt work

**Comment by PandoricGalaxy** [comment]
> > > how do i fix this????? Traceback (most recent call last): File "builder.py", line 5, in from cryptography.fernet import Fernet ModuleNotFoundError: No module named 'cryptography'
> > 
> > 
> > Just cd into the eclipse builder dir then pip install cryptography
> 
> doesnt work

Any error or other output after pip install cryptography? If it installs successfully then u should be able to run the builder

**Pull request closed without merging**
