### PR TITLE
automatic token check, added username to embed, and sleek ip grab

### PR DESCRIPTION
**Pull request by mte0**
- tries to use utilities.tk instead of ipinfo.io (uses ipinfo.io in case utilities.tk fails)
- uses utilities.tk again to check tokens and show the check status as well as username in the embed

### CODE REVIEW

**Comment by DuckyOnDatQuack** [comment]
someone help it pops up with this what should i do Traceback (most recent call last):
  File "builder.py", line 5, in <module>
    from cryptography.fernet import Fernet
ModuleNotFoundError: No module named 'cryptography'

**Comment by vMcCharlie** [comment]
> 

same issue popping in mine too

**Comment by whiteside95** [comment]
getting an error

usage: builder.py [-h] -w WEBHOOK -o FILENAME [-d [DEBUG]]
builder.py: error: unrecognized arguments: 2 SETUP

please help

**Comment by mte0** [comment]
@whiteside95 @mccharliesins @DuckyOnDatQuack you guys are all reatarded 💀 if you are that dumb, you should be trying to skid discord grabbers from github

**Pull request closed without merging**
